### ISSUE TITLE
Death runes coloring missing

### ISSUE THREAD

**Issue by danschne** [Tyriel-WoW/SuF-wotlk-classic#1]
I took a look at the code and compared the retail version with this one - am I reading this right that death runes are currently not colored any different? I am not an experienced WoW add on developer, but where is the color in the retail version of the code coming from (or is this add on not working with the recent retail version at all?)? It just says the following in ```runes.lua```:
```
local color = ShadowUF.db.profile.powerColors.RUNES // this is just some static value
```

**Comment by Tyriel-WoW** [comment]
the rune coloring was not present in the retail version of suf. i added it to this version, but since i'm new to dk i did not know about the death runes. maybe i find time to look further into it.

**Comment by danschne** [comment]
Alrighty. I am on vacation soon, but otherwise I can also try to help you.

**Comment by Tyriel-WoW** [comment]
The Death Runes should now work and have their own color. I also adjusted the sorting of the runes to the Blizzard UI.

**Comment by danschne** [comment]
Well thank you very much for responding so quickly - seems to work like a charm! :)
