### ISSUE TITLE
Text on top of each runes

### ISSUE THREAD

**Issue by Amortalist** [Tyriel-WoW/SuF-wotlk-classic#2]
Hey dude, first of all thanks for the effort to import Retail's runes bar to TLK, it works well however there is a text constantly showing in front of each runes which is super annoying, any chance to fix that ? 
![image](https://user-images.githubusercontent.com/47482996/188233710-cd390520-501a-4a1a-91d7-7ca65ff2a9e4.png)

**Comment by Tyriel-WoW** [comment]
Could you enlarge the width of the player frame so that it is possible to see exactly what is in the individual blocks?

**Comment by Amortalist** [comment]
Can't go wider than that : 
![image](https://user-images.githubusercontent.com/47482996/188275680-873073f1-b14d-4a05-9cfa-cac727d7da26.png)

**Comment by Tyriel-WoW** [comment]
I pushed a new version where i merged some missing parts of the rune-timers from the retail version of SuF. Maybe this will solve your problem.

**Comment by Amortalist** [comment]
Yup, works all right thanks a lot :)
